# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  desc "Lane to run the unit tests"
  lane :run_all_test do
    run_tests(device: "iPhone 13 Pro Max", scheme: "Actions")
  end

  desc "Lane to run the unit tests"
  lane :metrics do
    scan(scheme: "Actions", code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports", device: "iPhone 13 Pro Max")
    slather(cobertura_xml: true, jenkins: false, scheme: "Actions", build_directory: "./DerivedData", output_directory: "./reports", proj: "./Actions.xcodeproj")
    #lizard(source_folder: ".", language: "swift", export_type: "xml", report_file: "reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    #sonar
  end
 
  desc "Code Coverages"
  lane :coverage do
    xcov(project: "Actions.xcodeproj", scheme: "Actions", output_directory: "./reports/xcov", json_report: true) 
   end
end

