name: Running Testcases
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run:  bundle install
    - name: Metrics
      run: bundle exec fastlane metrics
