name: Running Testcases
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: |
       brew install sonarqube
       brew install sonar-scanner
       brew install lizard
       bundle install
    - name: Metrics
      run: bundle exec fastlane metrics
    - name: Code coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
        output-file: ./reports/report.html
