name: Running Testcases
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane run_all_test

    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Code Coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
        output-file: ./coverage/lcov.info
